# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Starling Integrity Docs
email: info@starlinglab.org
description: >- # this means to ignore newlines until "baseurl:"
  This site contains documentation for Staling Integrity project.
baseurl: "integrity-docs" # the subpath of your site, e.g. /blog
domain: "galargh.github.io"
url: "https://galargh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: starlinglab
github_username:  starlinglab

# Build settings
# theme: just-the-docs
remote_theme: just-the-docs/just-the-docs
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# https://just-the-docs.github.io/just-the-docs/docs/configuration/
aux_links:
  "Starling Lab":
    - "https://www.starlinglab.org/"
heading_anchors: true
collections:
  storage:
    permalink: "/:collection/:path/"
    output: true
just_the_docs:
  collections:
    storage:
      name: Storage Providers
    fake:
      # Trick just_the_docs to add collection headers even though there's only one real collection
      nav_exclude: true
      search_exclude: true
